sonar.projectKey=stephenlclarke_swift-nio-ssl
sonar.organization=stephenlclarke
sonar.projectName=swift-nio-ssl
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=Sources
sonar.tests=Tests
sonar.test.inclusions=Tests/**/*.swift
sonar.exclusions=.build/**,Sources/CNIOBoringSSL/**,Sources/CNIOBoringSSLShims/**
sonar.coverage.exclusions=Sources/CNIOBoringSSL/**,Sources/CNIOBoringSSLShims/**
sonar.coverageReportPaths=coverage.xml
sonar.qualitygate.wait=true
